# Generated by Django 6.1 on 2026-09-02 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.CharField(help_text="e.g. 'module.students'.", max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('default_enabled', models.BooleanField(default=False, help_text='Resolved value when no tenant override applies.')),
                ('is_kill_switch', models.BooleanField(default=False, help_text='When true, a tenant override can never turn this ON — only the platform default can enable it. Overrides may still force it off.')),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='TenantCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scope', models.CharField(max_length=32)),
                ('series', models.CharField(blank=True, max_length=64)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenant_counters',
                'indexes': [models.Index(fields=['tenant', 'scope'], name='tenant_counters_scope_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'scope', 'series'), name='tenant_counters_unique_series_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enabled', models.BooleanField()),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null means the override never expires.', null=True)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_overrides', to='tenancy.featureflag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenant_feature_overrides',
                'indexes': [models.Index(fields=['tenant', 'feature_flag'], name='tenant_feat_override_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'feature_flag'), name='tenant_feature_overrides_unique_flag_per_tenant')],
            },
        ),
    ]
