# Generated by Django 6.1 on 2026-09-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_tenantsettings_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='finance',
            field=models.JSONField(blank=True, default=dict, help_text="Fees/finance config, e.g. invoice_number_pattern, receipt_number_pattern, late-fee defaults. Its own namespace for the reason `hr` gives: a module's settings should not crowd another's, and `academic` is already the busiest key on this row."),
        ),
    ]
