# Generated by Django 6.1 on 2026-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_tenantsettings_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='communication',
            field=models.JSONField(blank=True, default=dict, help_text='Communication config, e.g. notice_number_pattern. Its own namespace for the reason `hr` and `finance` each got one.'),
        ),
    ]
