# Generated by Django 6.1 on 2026-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rls_policies'),
        ('school_organization', '0002_rls_policies'),
        ('staff_management', '0002_rls_policies'),
        ('tenancy', '0005_tenantsettings_hr'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['tenant', 'joining_date'], name='staff_tenant_joined_idx'),
        ),
    ]
