# Generated by Django 6.1 on 2026-09-07 03:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_organization', '0002_rls_policies'),
        ('tenancy', '0005_tenantsettings_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('scale_type', models.CharField(choices=[('percentage', 'Percentage'), ('letter', 'Letter grades'), ('gpa', 'GPA'), ('hybrid', 'Hybrid (letter and GPA)')], default='letter', max_length=20)),
                ('gpa_max', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 4.00 or 5.00. Required for a gpa or hybrid scale.', max_digits=4, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='One default per tenant; used when an exam names no scale.')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'grading_scales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('label', models.CharField(help_text='e.g. A+, B, Pass.', max_length=10)),
                ('min_percent', models.DecimalField(decimal_places=2, help_text='Inclusive.', max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, help_text='Inclusive.', max_digits=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='For GPA scales.', max_digits=4, null=True)),
                ('is_passing', models.BooleanField(default=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('grading_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='examinations.gradingscale')),
            ],
            options={
                'db_table': 'grade_bands',
                'ordering': ['sort_order', '-min_percent'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='e.g. "Term 1 Midterm".', max_length=150)),
                ('exam_type', models.CharField(choices=[('unit_test', 'Unit test'), ('midterm', 'Midterm'), ('final', 'Final'), ('practical', 'Practical'), ('custom', 'Custom')], max_length=30)),
                ('weightage_percent', models.DecimalField(decimal_places=2, default=100, help_text='Contribution to a consolidated term or session result.', max_digits=5)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('marks_entry', 'Marks entry'), ('processing', 'Processing'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='school_organization.academicsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('term', models.ForeignKey(blank=True, help_text='Null for a session-wide exam that no single term owns.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='school_organization.term')),
                ('grading_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='examinations.gradingscale')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-starts_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pass_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('has_practical', models.BooleanField(default=False)),
                ('practical_max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('practical_pass_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subject_weightage_percent', models.DecimalField(decimal_places=2, default=100, help_text="Weight within this exam's aggregate.", max_digits=5)),
                ('marks_entry_opens_at', models.DateTimeField(blank=True, null=True)),
                ('marks_entry_closes_at', models.DateTimeField(blank=True, null=True)),
                ('marks_locked_at', models.DateTimeField(blank=True, help_text='Set by :lock-marks; cleared by :unlock-marks.', null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='examinations.exam')),
                ('school_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='school_organization.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='school_organization.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'exam_subjects',
                'ordering': ['subject__name'],
                'indexes': [models.Index(fields=['tenant', 'exam'], name='exam_subjects_exam_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'exam', 'school_class', 'subject'), name='exam_subjects_unique_per_class_subject'), models.CheckConstraint(condition=models.Q(('max_marks__gt', 0)), name='exam_subjects_max_marks_positive'), models.CheckConstraint(condition=models.Q(('pass_marks__gte', 0), ('pass_marks__lte', models.F('max_marks'))), name='exam_subjects_pass_marks_within_max'), models.CheckConstraint(condition=models.Q(('has_practical', False), models.Q(('practical_max_marks__gt', 0), ('practical_max_marks__isnull', False)), _connector='OR'), name='exam_subjects_practical_max_present'), models.CheckConstraint(condition=models.Q(('practical_pass_marks__isnull', True), ('practical_pass_marks__lte', models.F('practical_max_marks')), _connector='OR'), name='exam_subjects_practical_pass_within_max'), models.CheckConstraint(condition=models.Q(('subject_weightage_percent__gt', 0), ('subject_weightage_percent__lte', 100)), name='exam_subjects_weightage_in_range'), models.CheckConstraint(condition=models.Q(('marks_entry_opens_at__isnull', True), ('marks_entry_closes_at__isnull', True), ('marks_entry_closes_at__gt', models.F('marks_entry_opens_at')), _connector='OR'), name='exam_subjects_entry_window_ordered')],
            },
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='grading_scales_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('tenant',), name='grading_scales_one_default'),
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scale_type__in', ('gpa', 'hybrid')), _negated=True), ('gpa_max__isnull', False), _connector='OR'), name='grading_scales_gpa_max_present'),
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.CheckConstraint(condition=models.Q(('gpa_max__isnull', True), ('gpa_max__gt', 0), _connector='OR'), name='grading_scales_gpa_max_positive'),
        ),
        migrations.AddIndex(
            model_name='gradeband',
            index=models.Index(fields=['tenant', 'grading_scale', 'min_percent'], name='grade_bands_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'grading_scale', 'label'), name='grade_bands_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.CheckConstraint(condition=models.Q(('min_percent__lt', models.F('max_percent'))), name='grade_bands_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.CheckConstraint(condition=models.Q(('max_percent__lte', 100), ('min_percent__gte', 0)), name='grade_bands_within_zero_to_hundred'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.CheckConstraint(condition=models.Q(('grade_point__isnull', True), ('grade_point__gte', 0), _connector='OR'), name='grade_bands_grade_point_not_negative'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['tenant', 'status'], name='exams_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['tenant', 'term'], name='exams_term_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'academic_session', 'name'), name='exams_name_unique_per_session'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ends_on__isnull', True), ('starts_on__isnull', True)), models.Q(('ends_on__isnull', False), ('starts_on__isnull', False)), _connector='OR'), name='exams_dates_set_together'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='exams_ends_on_after_starts_on'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('weightage_percent__gt', 0), ('weightage_percent__lte', 100)), name='exams_weightage_in_range'),
        ),
    ]
