# Generated by Django 6.1 on 2026-09-07 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_rls_policies'),
        ('files', '0002_rls_policies'),
        ('school_organization', '0002_rls_policies'),
        ('staff_management', '0002_rls_policies'),
        ('student_management', '0006_rls_policies'),
        ('tenancy', '0005_tenantsettings_hr'),
        ('timetable', '0003_leave_request_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('admit_card_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='generated', max_length=20)),
                ('issued_by', models.UUIDField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='examinations.exam')),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.file')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admit_cards', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'admit_cards',
                'ordering': ['admit_card_no'],
                'indexes': [models.Index(fields=['tenant', 'exam', 'status'], name='admit_cards_exam_status_idx'), models.Index(fields=['tenant', 'student'], name='admit_cards_student_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'exam', 'student'), name='admit_cards_one_per_student_per_exam'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'admit_card_no'), name='admit_cards_number_unique'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'revoked'), _negated=True), ('revoked_reason__isnull', False), _connector='OR'), name='admit_cards_revocation_has_a_reason')],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('instructions', models.CharField(blank=True, help_text='Printed on admit cards (§5.3).', max_length=500, null=True)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='examinations.examsubject')),
                ('invigilator_staff', models.ForeignKey(blank=True, db_column='invigilator_staff_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invigilations', to='staff_management.staff')),
                ('room', models.ForeignKey(blank=True, help_text='Null while a sitting is scheduled but not yet roomed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='timetable.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='school_organization.section')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'exam_schedules',
                'ordering': ['exam_date', 'start_time'],
                'indexes': [models.Index(fields=['tenant', 'exam_date', 'room'], name='exam_sched_date_room_idx'), models.Index(fields=['tenant', 'exam_date', 'invigilator_staff'], name='exam_sched_date_invig_idx'), models.Index(fields=['tenant', 'section', 'exam_date'], name='exam_sched_section_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'exam_subject', 'section'), name='exam_schedules_one_per_section'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='exam_schedules_end_after_start'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('room__isnull', False), ('status__in', ('scheduled', 'completed'))), fields=('tenant', 'room', 'exam_date', 'start_time'), name='exam_schedules_room_one_per_sitting'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('invigilator_staff__isnull', False), ('status__in', ('scheduled', 'completed'))), fields=('tenant', 'invigilator_staff', 'exam_date', 'start_time'), name='exam_schedules_invigilator_one_per_sitting')],
            },
        ),
    ]
