# Generated by Django 6.1 on 2026-09-07 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_rls_policies'),
        ('student_management', '0007_student_students_tenant_admitted_idx'),
        ('tenancy', '0005_tenantsettings_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('theory_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Null when the student was absent or exempt.', max_digits=6, null=True)),
                ('practical_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_absent', models.BooleanField(default=False, help_text='Mutually exclusive with a mark (§11).')),
                ('is_exempt', models.BooleanField(default=False, help_text='Excluded from the aggregate rather than scored zero.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('entered_by', models.UUIDField(help_text='The teacher or exam staff who entered it.')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.examsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'marks',
                'ordering': ['student__admission_number'],
                'indexes': [models.Index(fields=['tenant', 'student'], name='marks_student_idx'), models.Index(fields=['tenant', 'exam_subject', 'status'], name='marks_subject_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'exam_subject', 'student'), name='marks_one_per_student_per_exam_subject'), models.CheckConstraint(condition=models.Q(('theory_marks__isnull', True), ('theory_marks__gte', 0), _connector='OR'), name='marks_theory_not_negative'), models.CheckConstraint(condition=models.Q(('practical_marks__isnull', True), ('practical_marks__gte', 0), _connector='OR'), name='marks_practical_not_negative'), models.CheckConstraint(condition=models.Q(('is_absent', False), models.Q(('practical_marks__isnull', True), ('theory_marks__isnull', True)), _connector='OR'), name='marks_absent_has_no_score'), models.CheckConstraint(condition=models.Q(('is_absent', True), ('is_exempt', True), _negated=True), name='marks_absent_and_exempt_are_exclusive')],
            },
        ),
    ]
