# Generated by Django 6.1 on 2026-09-07 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0008_rls_policies'),
        ('school_organization', '0002_rls_policies'),
        ('tenancy', '0005_tenantsettings_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('school_class', models.ForeignKey(blank=True, db_column='class_id', help_text='Null means every level.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='school_organization.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to='school_organization.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'question_banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice'), ('true_false', 'True or false'), ('short_answer', 'Short answer'), ('long_answer', 'Long answer'), ('fill_blank', 'Fill in the blank'), ('numerical', 'Numerical')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('default_marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('options', models.JSONField(blank=True, help_text='Required for mcq and true_false.', null=True)),
                ('answer_key', models.JSONField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, help_text='The blueprint filter (§6).', max_length=150, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_generated', 'AI generated'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('is_approved', models.BooleanField(default=True, help_text='False on creation for ai_generated; flipped by :approve.')),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examinations.questionbank')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['tenant', 'school_class'], name='question_banks_class_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'subject', 'name'), name='question_banks_name_unique_per_subject'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['tenant', 'question_bank', 'difficulty'], name='questions_bank_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['tenant', 'question_bank', 'topic'], name='questions_bank_topic_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['tenant', 'source', 'is_approved'], name='questions_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('question_type__in', ('mcq', 'true_false')), _negated=True), ('options__isnull', False), _connector='OR'), name='questions_choice_types_have_options'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('default_marks__gt', 0)), name='questions_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('usage_count__gte', 0)), name='questions_usage_count_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'ai_generated'), _negated=True), ('is_approved', False), ('approved_by__isnull', False), _connector='OR'), name='questions_ai_approval_is_attributable'),
        ),
    ]
