# Generated by Django 6.1 on 2026-09-03 04:51

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.CharField(help_text="The client's Idempotency-Key header value.", max_length=255)),
                ('endpoint', models.CharField(help_text="Caller-chosen identifier, e.g. 'students:enroll'.", max_length=100)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'idempotency_records',
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='idempot_records_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'key', 'endpoint'), name='idempotency_records_unique_key_per_endpoint')],
            },
        ),
    ]
