# Generated by Django 6.1 on 2026-09-05 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0005_tenantsettings_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(help_text='users(id) — the recipient, tenant-checked at write time.')),
                ('event_key', models.CharField(help_text="Producing event, e.g. 'attendance.student-absent'.", max_length=100)),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('fees', 'Fees'), ('exams', 'Exams'), ('library', 'Library'), ('transport', 'Transport'), ('academic', 'Academic'), ('general', 'General'), ('emergency', 'Emergency')], default='general', max_length=30)),
                ('title', models.CharField(help_text='Rendered from the template.', max_length=200)),
                ('body', models.TextField(help_text='Rendered from the template.')),
                ('data', models.JSONField(blank=True, help_text='Deep-link payload (resource type/id, route).', null=True)),
                ('source_type', models.CharField(blank=True, help_text="Polymorphic origin, e.g. 'student'.", max_length=50, null=True)),
                ('source_id', models.UUIDField(blank=True, help_text='Origin row id, validated in the service layer.', null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=10)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('template_code', models.CharField(blank=True, help_text='Template used at render time — a soft reference by code, so it survives the template being edited or removed.', max_length=100, null=True)),
                ('provider', models.CharField(blank=True, help_text="Adapter name, e.g. 'console', 'ses'.", max_length=50, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=150, null=True)),
                ('recipient_address', models.CharField(help_text='Email/phone/device token, stored masked — see services.mask_address.', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('skipped', 'Skipped')], default='queued', max_length=15)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'db_table': 'delivery_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'user_id', 'read_at', '-created_at'], name='notifications_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'source_type', 'source_id'], name='notifications_source_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['tenant', 'status', 'last_attempt_at'], name='delivery_logs_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['tenant', 'notification'], name='delivery_logs_notif_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['provider_message_id'], name='delivery_logs_provider_idx'),
        ),
    ]
