# Generated by Django 6.1 on 2026-09-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rls_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='body',
            field=models.TextField(blank=True, help_text="This channel's own rendering — NULL for in_app, which reuses Notification.body instead.", null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='subject',
            field=models.CharField(blank=True, help_text="This channel's own rendering — NULL for in_app, which has no separate send and reuses Notification.title instead. See services.notify's per-channel rendering.", max_length=200, null=True),
        ),
    ]
