# Generated by Django 6.1 on 2026-09-05 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_organization', '0002_rls_policies'),
        ('staff_management', '0002_rls_policies'),
        ('tenancy', '0005_tenantsettings_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='e.g. "Period 1", "Recess".', max_length=50)),
                ('sequence', models.PositiveSmallIntegerField(help_text='Daily order, 1-based.')),
                ('start_time', models.TimeField(help_text='Local to the tenant/campus timezone.')),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False, help_text='Breaks are never schedulable (§5.1).')),
                ('weekdays', models.JSONField(blank=True, help_text="Applicable weekdays as 0-6; null = the tenant's working days.", null=True)),
                ('campus', models.ForeignKey(blank=True, help_text='Null = every campus.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='school_organization.campus')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'periods',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Lab'), ('library', 'Library'), ('auditorium', 'Auditorium'), ('sports', 'Sports'), ('office', 'Office'), ('other', 'Other')], default='classroom', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=80, null=True)),
                ('floor', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='school_organization.campus')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['campus_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text="0-6; the week's start comes from tenant configuration.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Null = current. Set on a mid-session revision.', null=True)),
                ('notes', models.CharField(blank=True, help_text='Per-cell note, e.g. "double period".', max_length=200, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='school_organization.academicsession')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='timetable.period')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='timetable.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='school_organization.section')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='staff_management.staff')),
                ('subject', models.ForeignKey(blank=True, help_text='Null for homeroom/assembly slots.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='school_organization.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'timetable_slots',
                'ordering': ['day_of_week', 'period__sequence'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(help_text="Must fall on the slot's weekday and inside the session.")),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('leave_request_id', models.UUIDField(blank=True, help_text='leave_requests(id) — a plain UUID, not an FK: the attendance module that owns that table has not shipped yet.', null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('absent_staff', models.ForeignKey(db_column='absent_staff_id', on_delete=django.db.models.deletion.PROTECT, related_name='absences_covered', to='staff_management.staff')),
                ('period', models.ForeignKey(help_text='Copied from the slot; see the class docstring for why it is denormalised.', on_delete=django.db.models.deletion.PROTECT, related_name='substitutions', to='timetable.period')),
                ('room', models.ForeignKey(blank=True, help_text="Ad-hoc room change for this date only (§6). Null = keep the slot's room.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitutions', to='timetable.room')),
                ('substitute_staff', models.ForeignKey(db_column='substitute_staff_id', on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_taken', to='staff_management.staff')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('timetable_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions', to='timetable.timetableslot')),
            ],
            options={
                'db_table': 'teacher_substitutions',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['tenant', 'campus'], name='periods_tenant_campus_idx'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'campus', 'sequence'), name='periods_unique_sequence_per_campus', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='periods_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['tenant', 'campus', 'room_type'], name='rooms_campus_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'campus', 'code'), name='rooms_unique_code_per_campus'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['tenant', 'section', 'status'], name='slots_section_status_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['tenant', 'academic_session', 'staff'], name='slots_session_staff_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('effective_to__isnull', True), ('status', 'published')), fields=('tenant', 'academic_session', 'section', 'day_of_week', 'period'), name='slots_one_per_section_cell'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('effective_to__isnull', True), ('staff__isnull', False), ('status', 'published')), fields=('tenant', 'academic_session', 'staff', 'day_of_week', 'period'), name='slots_teacher_not_double_booked'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('effective_to__isnull', True), ('room__isnull', False), ('status', 'published')), fields=('tenant', 'academic_session', 'room', 'day_of_week', 'period'), name='slots_room_not_double_booked'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='slots_day_of_week_range'),
        ),
        migrations.AddIndex(
            model_name='teachersubstitution',
            index=models.Index(fields=['tenant', 'substitute_staff', 'date'], name='subs_substitute_date_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubstitution',
            index=models.Index(fields=['tenant', 'absent_staff', 'date'], name='subs_absent_date_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubstitution',
            index=models.Index(fields=['tenant', 'room', 'date'], name='subs_room_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachersubstitution',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'timetable_slot', 'date'), name='substitutions_one_per_slot_per_date'),
        ),
        migrations.AddConstraint(
            model_name='teachersubstitution',
            constraint=models.CheckConstraint(condition=models.Q(('substitute_staff', models.F('absent_staff')), _negated=True), name='substitutions_substitute_differs_from_absentee'),
        ),
        migrations.AddConstraint(
            model_name='teachersubstitution',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ('proposed', 'confirmed'))), fields=('tenant', 'substitute_staff', 'date', 'period'), name='subs_substitute_one_per_period'),
        ),
        migrations.AddConstraint(
            model_name='teachersubstitution',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('room__isnull', False), ('status__in', ('proposed', 'confirmed'))), fields=('tenant', 'room', 'date', 'period'), name='subs_room_one_per_period'),
        ),
    ]
