# Generated by Django 6.1 on 2026-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_organization', '0002_rls_policies'),
        ('tenancy', '0005_tenantsettings_hr'),
        ('timetable', '0003_leave_request_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['tenant', 'name'], name='rooms_tenant_name_idx'),
        ),
    ]
