# Generated by Django 6.1 on 2026-09-03 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('job_type', models.CharField(help_text="e.g. 'import.students', 'export.students', 'id-cards.generate'.", max_length=60)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Input parameters (PII-minimized).')),
                ('result', models.JSONField(blank=True, help_text='Result summary, e.g. result_file_id.', null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'background_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='background_jobs_status_idx'), models.Index(fields=['tenant', 'job_type'], name='background_jobs_type_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='background_jobs_unique_idempotency_key'), models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='background_jobs_progress_range')],
            },
        ),
    ]
