# Generated by Django 6.1 on 2026-09-02 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_organization', '0002_rls_policies'),
        ('tenancy', '0003_featureflag_tenantcounter_tenantfeatureoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('admission_number', models.CharField(help_text="Generated per the tenant's admission-number pattern. Immutable after creation (§11) — see services.assert_admission_number_immutable.", max_length=32)),
                ('user_id', models.UUIDField(blank=True, help_text='users(id) — portal account, tenant-checked at write time.', null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unspecified', 'Unspecified')], max_length=20)),
                ('photo_file_id', models.UUIDField(blank=True, help_text='files(id) — promoted when core.files lands.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('admission_date', models.DateField()),
                ('blood_group', models.CharField(blank=True, max_length=8, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80, null=True)),
                ('religion', models.CharField(blank=True, help_text='Optional/sensitive; a tenant may disable.', max_length=80, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('medical_notes', models.TextField(blank=True, help_text='Restricted visibility — see serializers.StudentSerializer.to_representation and core.audit.services._REDACTED_FIELDS.', null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school_organization.campus')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school_organization.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='students_tenant_status_idx'), models.Index(fields=['tenant', 'campus'], name='students_tenant_campus_idx'), models.Index(fields=['tenant', 'house'], name='students_tenant_house_idx'), models.Index(fields=['tenant', 'last_name', 'first_name'], name='students_tenant_name_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'admission_number'), name='students_unique_admission_number_per_tenant'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('user_id__isnull', False)), fields=('tenant', 'user_id'), name='students_unique_user_per_tenant'), models.CheckConstraint(condition=models.Q(('admission_date__gte', models.F('date_of_birth'))), name='students_admission_after_birth')],
            },
        ),
    ]
