# Generated by Django 6.1 on 2026-09-03 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rls_policies'),
        ('student_management', '0002_rls_policies'),
        ('tenancy', '0004_rls_policies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo_file_id',
        ),
        migrations.AddField(
            model_name='student',
            name='photo_file',
            field=models.ForeignKey(blank=True, db_column='photo_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.file'),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, help_text='users(id) — portal account, tenant-checked at write time.', null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='Primary contact; indexed for duplicate matching.', max_length=32)),
                ('alt_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('national_id', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('photo_file', models.ForeignKey(blank=True, db_column='photo_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.file')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'guardians',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('document_type', models.CharField(help_text='Tenant-extensible; seeded values: birth_certificate, prior_transfer_certificate, immunization_record, photo_id, prior_report_card, other.', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_by', models.UUIDField(blank=True, help_text='users(id).', null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('file', models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.file')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'student_documents',
                'ordering': ['student_id', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('legal_guardian', 'Legal guardian'), ('other', 'Other')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_fee_responsible', models.BooleanField(default=False)),
                ('can_pick_up', models.BooleanField(default=True)),
                ('receives_communications', models.BooleanField(default=True)),
                ('has_portal_access', models.BooleanField(default=True)),
                ('access_revoked_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_links', to='student_management.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_links', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'student_guardians',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=32)),
                ('alt_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Call order; 1 = first.')),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_contacts', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'emergency_contacts',
                'ordering': ['student_id', 'priority'],
                'indexes': [models.Index(fields=['tenant', 'student', 'priority'], name='emergency_contacts_student_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('priority__gte', 1)), name='emergency_contacts_priority_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['tenant', 'phone'], name='guardians_tenant_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['tenant', 'email'], name='guardians_tenant_email_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['tenant', 'last_name', 'first_name'], name='guardians_tenant_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('user_id__isnull', False)), fields=('tenant', 'user_id'), name='guardians_unique_user_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['tenant', 'student', 'document_type'], name='student_documents_type_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['tenant', 'verification_status'], name='student_documents_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(condition=models.Q(('expires_at__isnull', False)), fields=['tenant', 'expires_at'], name='student_documents_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'pending'), ('verified_at__isnull', True), ('verified_by__isnull', True)), models.Q(models.Q(('verification_status', 'pending'), _negated=True), ('verified_at__isnull', False), ('verified_by__isnull', False)), _connector='OR'), name='student_documents_verifier_required_when_decided'),
        ),
        migrations.AddIndex(
            model_name='studentguardian',
            index=models.Index(fields=['tenant', 'guardian'], name='student_guardians_guardian_idx'),
        ),
        migrations.AddIndex(
            model_name='studentguardian',
            index=models.Index(fields=['tenant', 'student'], name='student_guardians_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'student', 'guardian'), name='student_guardians_unique_link_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True)), fields=('tenant', 'student'), name='student_guardians_one_primary_per_student'),
        ),
    ]
