# Generated by Django 6.1 on 2026-09-03 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_organization', '0002_rls_policies'),
        ('student_management', '0004_rls_policies'),
        ('tenancy', '0004_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=16, null=True)),
                ('enrollment_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Set when status leaves active.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('retained', 'Retained'), ('transferred_out', 'Transferred out'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='school_organization.academicsession')),
                ('school_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='school_organization.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='school_organization.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'student_enrollments',
                'ordering': ['-enrollment_date'],
                'indexes': [models.Index(fields=['tenant', 'section', 'status'], name='student_enroll_section_idx'), models.Index(fields=['tenant', 'academic_session', 'school_class'], name='student_enroll_sess_class_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'student', 'academic_session'), name='student_enrollments_unique_per_session'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('roll_number__isnull', False)), fields=('tenant', 'section', 'roll_number'), name='student_enrollments_unique_roll_per_section')],
            },
        ),
        migrations.CreateModel(
            name='StudentTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transfer_type', models.CharField(choices=[('inter_campus', 'Inter-campus'), ('outgoing', 'Outgoing'), ('incoming', 'Incoming')], max_length=20)),
                ('external_school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('effective_date', models.DateField()),
                ('decided_by', models.UUIDField(blank=True, help_text='users(id).', null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_document_id', models.UUIDField(blank=True, help_text='generated_documents(id) — Tier 7, not built yet.', null=True)),
                ('from_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='school_organization.campus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('to_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='school_organization.campus')),
            ],
            options={
                'db_table': 'student_transfers',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['tenant', 'student'], name='student_transfers_student_idx'), models.Index(fields=['tenant', 'status'], name='student_transfers_status_idx'), models.Index(fields=['tenant', 'effective_date'], name='student_transfers_eff_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('status', 'requested')), models.Q(models.Q(('status', 'requested'), _negated=True), ('decided_at__isnull', False), ('decided_by__isnull', False)), _connector='OR'), name='student_transfers_decider_required_when_decided')],
            },
        ),
    ]
