# Generated by Django 6.1 on 2026-09-06 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_organization', '0002_rls_policies'),
        ('student_management', '0006_rls_policies'),
        ('tenancy', '0005_tenantsettings_hr'),
        ('timetable', '0002_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attendance_date', models.DateField(help_text="Calendar date in the tenant's timezone.")),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day'), ('excused', 'Excused'), ('on_leave', 'On leave')], max_length=20)),
                ('check_in_time', models.TimeField(blank=True, help_text='Set for a late arrival.', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Set for an early departure or a half day.', null=True)),
                ('late_minutes', models.IntegerField(blank=True, help_text='Computed server-side from the tenant day window (§11); never client-supplied.', null=True)),
                ('leave_request_id', models.UUIDField(blank=True, help_text="leave_requests(id) — a plain UUID, not an FK: the table ships in this module's second PR. Becomes a real foreign key there.", null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('device', 'Device')], default='manual', max_length=20)),
                ('marked_by', models.UUIDField(help_text='users(id) — the marking actor.')),
                ('is_locked', models.BooleanField(default=False, help_text='True past the lock window; changes then need a correction (§5.5).')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_attendance', to='school_organization.academicsession')),
                ('period', models.ForeignKey(blank=True, help_text='Null = daily attendance. Set only when the tenant runs period mode.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_attendance', to='timetable.period')),
                ('section', models.ForeignKey(help_text="The section at the time of marking, not the student's current one.", on_delete=django.db.models.deletion.PROTECT, related_name='student_attendance', to='school_organization.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'student_attendance',
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('subject_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('requested_by', models.UUIDField(help_text='users(id).')),
                ('old_values', models.JSONField(help_text='Status and times before the change.')),
                ('new_values', models.JSONField(help_text='Proposed status and times.')),
                ('reason', models.CharField(help_text='Mandatory justification (§6).', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_by', models.UUIDField(blank=True, help_text='users(id); must differ from requested_by (§11).', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('student_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='attendance.studentattendance')),
            ],
            options={
                'db_table': 'attendance_corrections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['tenant', 'section', 'attendance_date'], name='stu_att_section_date_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['tenant', 'attendance_date', 'status'], name='stu_att_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['tenant', 'student', 'attendance_date'], name='stu_att_student_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('period__isnull', True)), fields=('tenant', 'student', 'attendance_date'), name='student_attendance_one_per_day'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('period__isnull', False)), fields=('tenant', 'student', 'attendance_date', 'period'), name='student_attendance_one_per_period'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.CheckConstraint(condition=models.Q(('late_minutes__isnull', True), ('late_minutes__gte', 0), _connector='OR'), name='student_attendance_late_minutes_not_negative'),
        ),
        migrations.AddIndex(
            model_name='attendancecorrection',
            index=models.Index(fields=['tenant', 'status'], name='att_corr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancecorrection',
            index=models.Index(fields=['tenant', 'student_attendance'], name='att_corr_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrection',
            constraint=models.CheckConstraint(condition=models.Q(('student_attendance__isnull', False)), name='attendance_corrections_has_a_target'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrection',
            constraint=models.CheckConstraint(condition=models.Q(('subject_type', 'student')), name='attendance_corrections_student_targets_only'),
        ),
    ]
