# Generated by Django 6.1 on 2026-09-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rls_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('system', 'System'), ('import', 'Import'), ('device', 'Device')], default='manual', max_length=20),
        ),
    ]
