"""`staff_attendance`, and the correction target it completes.

The marking PR shipped `attendance_corrections` with only `student_attendance` to
point at and a CHECK that said exactly that; this widens both to the two-target
shape `entities/attendance.md` specifies. Dropping and recreating a CHECK is
ordinarily a lock-taking rewrite, and it is cheap here for the reason that PR
recorded when it made the narrower call: `module.attendance` ships
`default_enabled=False`, so no tenant has rows in this table yet.

`subject_type` gains a constraint it never had — that it agrees with whichever
target column is set. A denormalised discriminator that can disagree with the
thing it discriminates is a second source of truth, and it is the one an
approver's queue filters on.
"""


# Generated by Django 6.1 on 2026-09-06 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rls_policies'),
        ('staff_management', '0002_rls_policies'),
        ('tenancy', '0005_tenantsettings_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attendance_date', models.DateField(help_text="Calendar date in the tenant's timezone.")),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day'), ('on_leave', 'On leave'), ('holiday', 'Holiday')], max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Must be later than check_in_time (§11).', null=True)),
                ('late_minutes', models.IntegerField(blank=True, help_text='Computed server-side from the tenant work-day window; never client-supplied.', null=True)),
                ('early_departure_minutes', models.IntegerField(blank=True, help_text='Computed server-side, like late_minutes.', null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('self', 'Self check-in'), ('import', 'Import'), ('device', 'Device')], default='manual', max_length=20)),
                ('marked_by', models.UUIDField(help_text='users(id) — the recording actor.')),
                ('is_locked', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'staff_attendance',
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='attendancecorrection',
            name='attendance_corrections_has_a_target',
        ),
        migrations.RemoveConstraint(
            model_name='attendancecorrection',
            name='attendance_corrections_student_targets_only',
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='leave_request',
            field=models.ForeignKey(blank=True, db_column='leave_request_id', help_text="Set when status is on_leave; written by hr-leave's approval flow.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_attendance', to='attendance.leaverequest'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='staff_management.staff'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='attendancecorrection',
            name='staff_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='attendance.staffattendance'),
        ),
        migrations.AddIndex(
            model_name='attendancecorrection',
            index=models.Index(fields=['tenant', 'staff_attendance'], name='att_corr_staff_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('staff_attendance__isnull', True), ('student_attendance__isnull', False)), models.Q(('staff_attendance__isnull', False), ('student_attendance__isnull', True)), _connector='OR'), name='attendance_corrections_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student_attendance__isnull', False), ('subject_type', 'student')), models.Q(('staff_attendance__isnull', False), ('subject_type', 'staff')), _connector='OR'), name='attendance_corrections_subject_type_matches_target'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['tenant', 'attendance_date', 'status'], name='staff_att_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['tenant', 'staff', 'attendance_date'], name='staff_att_staff_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'staff', 'attendance_date'), name='staff_attendance_one_per_day'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_time__isnull', True), ('check_in_time__isnull', True), ('check_out_time__gt', models.F('check_in_time')), _connector='OR'), name='staff_attendance_check_out_after_check_in'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.CheckConstraint(condition=models.Q(('late_minutes__isnull', True), ('late_minutes__gte', 0), _connector='OR'), name='staff_attendance_late_minutes_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.CheckConstraint(condition=models.Q(('early_departure_minutes__isnull', True), ('early_departure_minutes__gte', 0), _connector='OR'), name='staff_attendance_early_minutes_not_negative'),
        ),
    ]
