import {
  addEmergencyContact,
  createStudent,
  deleteDocument,
  fetchDocuments,
  fetchEmergencyContacts,
  fetchStudentById,
  fetchStudentsPage,
  getDocumentDownloadUrl,
  updateStudent,
  uploadDocumentRecord,
  verifyDocument,
  withdrawStudent,
} from "./students-service";

export const StudentsService = {
  fetchStudentsPage,
  fetchStudentById,
  createStudent,
  updateStudent,
  withdrawStudent,
  fetchEmergencyContacts,
  addEmergencyContact,
  fetchDocuments,
  uploadDocumentRecord,
  deleteDocument,
  verifyDocument,
  getDocumentDownloadUrl,
};
export type {
  AddEmergencyContactInput,
  CreateStudentInput,
  DocumentVerificationDecision,
  EmergencyContactRecord,
  StudentDocumentRecord,
  StudentRecord,
  StudentsPageQuery,
  UpdateStudentInput,
  UploadDocumentInput,
  WithdrawStudentInput,
} from "./students-service";
