import {
  addEmergencyContact,
  changeStudentSection,
  createStudent,
  deleteDocument,
  enrollStudent,
  fetchDocuments,
  fetchEmergencyContacts,
  fetchStudentById,
  fetchStudentHistory,
  fetchStudentsPage,
  generateIdCards,
  getDocumentDownloadUrl,
  triggerStudentExport,
  triggerStudentImport,
  updateStudent,
  uploadDocumentRecord,
  verifyDocument,
  withdrawStudent,
} from "./students-service";

export const StudentsService = {
  fetchStudentsPage,
  fetchStudentById,
  createStudent,
  updateStudent,
  withdrawStudent,
  enrollStudent,
  changeStudentSection,
  fetchStudentHistory,
  fetchEmergencyContacts,
  addEmergencyContact,
  fetchDocuments,
  uploadDocumentRecord,
  deleteDocument,
  verifyDocument,
  getDocumentDownloadUrl,
  triggerStudentImport,
  triggerStudentExport,
  generateIdCards,
};
export type {
  AddEmergencyContactInput,
  ChangeStudentSectionInput,
  CreateStudentInput,
  DocumentVerificationDecision,
  EmergencyContactRecord,
  EnrollStudentInput,
  IdCardGenerateBody,
  IdCardJobResult,
  StudentDocumentRecord,
  StudentEnrollmentRecord,
  StudentHistoryEvent,
  StudentRecord,
  StudentsPageQuery,
  UpdateStudentInput,
  UploadDocumentInput,
  WithdrawStudentInput,
} from "./students-service";
