# Generated by Django 6.1 on 2026-09-08 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0007_tenantsettings_communication'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(help_text='users(id) — tenant-checked at write time.')),
                ('event_category', models.CharField(choices=[('attendance', 'Attendance'), ('fees', 'Fees'), ('exams', 'Exams'), ('library', 'Library'), ('transport', 'Transport'), ('academic', 'Academic'), ('general', 'General'), ('emergency', 'Emergency')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notification_preferences',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'user_id', 'event_category', 'channel'), name='notification_preferences_unique_live')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplateOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(help_text="Matches a core.notifications trigger's template_code.", max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('locale', models.CharField(default='en', help_text="BCP-47 tag. Only 'en' is ever created in this plan — see the module's §20 register for the deferred locale-variant work.", max_length=10)),
                ('subject', models.CharField(blank=True, help_text='NULL for a subjectless channel (SMS).', max_length=200, null=True)),
                ('body', models.TextField()),
                ('variables', models.JSONField(help_text='Copied from the platform template at creation.')),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive falls back to the platform default, not to nothing.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notification_templates',
                'indexes': [models.Index(fields=['tenant', 'code', 'channel'], name='notif_tmpl_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'code', 'channel', 'locale'), name='notification_templates_unique_live')],
            },
        ),
    ]
