# Generated by Django 6.1 on 2026-09-09 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_rls_policies'),
        ('tenancy', '0007_tenantsettings_communication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Rich text (sanitized HTML/Markdown).')),
                ('audience_type', models.CharField(choices=[('all', 'All'), ('staff', 'Staff'), ('students', 'Students'), ('guardians', 'Guardians'), ('class', 'Class'), ('section', 'Section'), ('custom', 'Custom')], default='all', max_length=20)),
                ('audience_filter', models.JSONField(blank=True, help_text="Role slugs / class, section, house, campus ids / user ids for 'custom'.", null=True)),
                ('campus_id', models.UUIDField(blank=True, help_text='campuses(id); NULL means all campuses.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_emergency', models.BooleanField(default=False, help_text='Emergency posts bypass preferences on fan-out.')),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Hidden from feeds after expiry.', null=True)),
                ('show_on_website', models.BooleanField(default=False)),
                ('attachments', models.JSONField(blank=True, help_text='Array of files.id.', null=True)),
                ('published_by', models.UUIDField(blank=True, help_text='users(id).', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'announcements',
                'indexes': [models.Index(fields=['tenant', 'status', 'publish_at'], name='announcements_status_idx'), models.Index(fields=['tenant', 'campus_id'], name='announcements_campus_idx'), models.Index(condition=models.Q(('show_on_website', True)), fields=['tenant', 'show_on_website'], name='announcements_website_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notice_no', models.CharField(blank=True, help_text='Assigned at publish from the tenant sequence.', max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notice_type', models.CharField(choices=[('general', 'General'), ('circular', 'Circular'), ('event', 'Event'), ('urgent', 'Urgent')], default='general', max_length=20)),
                ('audience_type', models.CharField(choices=[('all', 'All'), ('staff', 'Staff'), ('students', 'Students'), ('guardians', 'Guardians'), ('class', 'Class'), ('section', 'Section'), ('custom', 'Custom')], default='all', max_length=20)),
                ('audience_filter', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('requires_acknowledgment', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('show_on_website', models.BooleanField(default=False)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, help_text='users(id); must differ from created_by.', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notices',
                'indexes': [models.Index(fields=['tenant', 'status', 'publish_at'], name='notices_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('notice_no__isnull', False)), fields=('tenant', 'notice_no'), name='notices_unique_notice_no_live')],
            },
        ),
    ]
