# Generated by Django 6.1 on 2026-09-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_rls_policies'),
        ('tenancy', '0007_tenantsettings_communication'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='notices_approver_not_drafter'),
        ),
    ]
