# Generated by Django 6.1 on 2026-09-07 18:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_organization', '0002_rls_policies'),
        ('tenancy', '0005_tenantsettings_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('admission', 'Admission'), ('transport', 'Transport'), ('library', 'Library'), ('exam', 'Exam'), ('fine', 'Fine'), ('other', 'Other')], default='other', max_length=20)),
                ('is_refundable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive heads are excluded from new structures.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fee_heads',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='school_organization.academicsession')),
                ('campus', models.ForeignKey(blank=True, help_text='Null means all campuses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='school_organization.campus')),
                ('school_class', models.ForeignKey(blank=True, db_column='class_id', help_text='Null means the structure applies session-wide.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='school_organization.class')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fee_structures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('one_time', 'One time'), ('monthly', 'Monthly'), ('per_term', 'Per term'), ('annual', 'Annual')], default='monthly', max_length=15)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, help_text='Day-of-month due rule for monthly schedules.', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Fixed due date for one_time and annual schedules.', null=True)),
                ('late_fee_policy', models.JSONField(blank=True, help_text='Grace days and fixed/percent late fee, tenant-configured. Read by the overdue sweep; absent means no automatic late fee.', null=True)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='fees_finance.feehead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('term', models.ForeignKey(blank=True, help_text='Required when frequency is per_term.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='school_organization.term')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='fees_finance.feestructure')),
            ],
            options={
                'db_table': 'fee_schedules',
                'ordering': ['fee_head__code'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=15)),
                ('is_system', models.BooleanField(default=False, help_text='Seeded at provisioning; cannot be deleted (see the delete constraint).')),
                ('is_active', models.BooleanField(default=True, help_text='Archived accounts reject new postings but keep their history.')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='fees_finance.ledgeraccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ledger_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='feehead',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_heads', to='fees_finance.ledgeraccount'),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, help_text='Groups the balanced lines of one posting. Assigned by ledger.post_transaction.')),
                ('entry_date', models.DateField(help_text='Posting date, which is not always the creation date.')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('expense', 'Expense'), ('payroll_run', 'Payroll run'), ('fine', 'Fine'), ('manual', 'Manual journal'), ('reversal', 'Reversal')], max_length=30)),
                ('reference_id', models.UUIDField(blank=True, help_text='The origin record, per reference_type. Null for a manual journal, which has no platform record behind it.', null=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('reversed_by_transaction_id', models.UUIDField(blank=True, help_text='Set when a reversal supersedes this posting. The only mutable column.', null=True)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='fees_finance.ledgeraccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-entry_date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['tenant', 'academic_session', 'status'], name='fee_structu_tenant__8241e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'academic_session', 'school_class', 'campus', 'name'), name='fee_structures_scope_name_unique', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['tenant', 'fee_structure'], name='fee_schedul_tenant__fc7c82_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'fee_structure', 'fee_head', 'frequency', 'term'), name='fee_schedules_line_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fee_schedules_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frequency', 'per_term'), ('term__isnull', False)), models.Q(models.Q(('frequency', 'per_term'), _negated=True), ('term__isnull', True)), _connector='OR'), name='fee_schedules_term_matches_frequency'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('due_day__isnull', False), ('frequency', 'monthly')), models.Q(models.Q(('frequency', 'monthly'), _negated=True), ('due_day__isnull', True)), _connector='OR'), name='fee_schedules_due_day_matches_frequency'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.CheckConstraint(condition=models.Q(('due_day__isnull', True), models.Q(('due_day__gte', 1), ('due_day__lte', 28)), _connector='OR'), name='fee_schedules_due_day_in_every_month'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('due_date__isnull', False), ('frequency__in', ['one_time', 'annual'])), models.Q(models.Q(('frequency__in', ['one_time', 'annual']), _negated=True), ('due_date__isnull', True)), _connector='OR'), name='fee_schedules_due_date_matches_frequency'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['tenant', 'account_type'], name='ledger_acco_tenant__f35dc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'code'), name='ledger_accounts_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), _negated=True), ('deleted_at__isnull', True), _connector='OR'), name='ledger_accounts_system_not_deleted'),
        ),
        migrations.AddIndex(
            model_name='feehead',
            index=models.Index(fields=['tenant', 'category'], name='fee_heads_tenant__cb78ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='feehead',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'code'), name='fee_heads_code_unique'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'transaction_id'], name='ledger_entr_tenant__6d73e5_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'ledger_account', 'entry_date'], name='ledger_entr_tenant__749229_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'reference_type', 'reference_id'], name='ledger_entr_tenant__cfc9f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='ledger_entries_exactly_one_side'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ledger_entries_no_negative_amounts'),
        ),
    ]
