# Generated by Django 6.1 on 2026-09-07 19:13

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_finance', '0002_rls_policies'),
        ('school_organization', '0002_rls_policies'),
        ('student_management', '0007_student_students_tenant_admitted_idx'),
        ('tenancy', '0006_tenantsettings_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invoice_no', models.CharField(max_length=30)),
                ('period_label', models.CharField(blank=True, help_text='e.g. "2026-09" or "Term 1". Part of the duplicate guard.', max_length=40, null=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fine_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('canceled_reason', models.TextField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_invoices', to='school_organization.academicsession')),
                ('fee_structure', models.ForeignKey(blank=True, help_text='Null for an ad-hoc invoice raised outside any structure.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fees_finance.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_invoices', to='student_management.student')),
                ('student_enrollment', models.ForeignKey(blank=True, help_text='Class/section at billing time. A snapshot, not a live lookup.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_invoices', to='student_management.studentenrollment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fee_invoices',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source_type', models.CharField(choices=[('schedule', 'Fee schedule'), ('fine', 'Fine'), ('adjustment', 'Adjustment')], default='schedule', max_length=20)),
                ('source_id', models.UUIDField(blank=True, help_text='The fee_schedules or fines row per source_type. Null for an adjustment.', null=True)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='fees_finance.feehead')),
                ('fee_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fees_finance.feeinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fee_invoice_lines',
                'ordering': ['fee_head__code'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fine_type', models.CharField(choices=[('late_fee', 'Late fee'), ('library', 'Library'), ('transport', 'Transport'), ('damage', 'Damage'), ('discipline', 'Discipline'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('source_module', models.CharField(blank=True, help_text='Originating module slug, e.g. `library`. Null for a hand-raised fine.', max_length=30, null=True)),
                ('source_reference', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=15)),
                ('waived_by', models.UUIDField(blank=True, null=True)),
                ('waived_reason', models.TextField(blank=True, null=True)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='fees_finance.feehead')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('scholarship_type', models.CharField(choices=[('merit', 'Merit'), ('need', 'Need'), ('sports', 'Sports'), ('staff_ward', 'Staff ward'), ('other', 'Other')], default='merit', max_length=20)),
                ('coverage_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent (0-100) or a fixed amount for the session.', max_digits=12)),
                ('sponsor', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('approved', 'Approved'), ('active', 'Active'), ('ended', 'Ended'), ('revoked', 'Revoked')], default='approved', max_length=15)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarships', to='school_organization.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarships', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'scholarships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent (0-100) or a fixed amount.', max_digits=12)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='school_organization.academicsession')),
                ('fee_head', models.ForeignKey(blank=True, help_text='Null applies the discount to every head.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='fees_finance.feehead')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_discounts', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'discounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'student', 'academic_session', 'status'], name='discounts_tenant__1faa1f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='discounts_value_positive'), models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percent'), _negated=True), ('value__lte', 100), _connector='OR'), name='discounts_percent_within_range'), models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='discounts_validity_ordered'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('approved_by__isnull', False), _connector='OR'), name='discounts_active_is_attributable')],
            },
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['tenant', 'student', 'status'], name='fee_invoice_tenant__96c0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['tenant', 'due_date'], name='fee_invoice_tenant__7a6547_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'invoice_no'), name='fee_invoices_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('status', 'canceled'), _negated=True)), fields=('tenant', 'student', 'fee_structure', 'period_label'), name='fee_invoices_no_duplicate_period', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('issue_date'))), name='fee_invoices_due_after_issue'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('discount_total__gte', 0), ('fine_total__gte', 0), ('paid_total__gte', 0)), name='fee_invoices_no_negative_totals'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('balance_due', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('discount_total')), '+', models.F('fine_total')), '-', models.F('paid_total')))), name='fee_invoices_balance_is_derived'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_total__lte', models.F('subtotal'))), name='fee_invoices_discount_within_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'canceled'), _negated=True), models.Q(('canceled_reason__isnull', False), models.Q(('canceled_reason', ''), _negated=True)), _connector='OR'), name='fee_invoices_cancellation_is_attributable'),
        ),
        migrations.AddIndex(
            model_name='feeinvoiceline',
            index=models.Index(fields=['tenant', 'fee_invoice'], name='fee_invoice_tenant__429507_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoiceline',
            index=models.Index(fields=['tenant', 'source_type', 'source_id'], name='fee_invoice_tenant__92fe33_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('discount_amount__gte', 0)), name='fee_invoice_lines_no_negative_amounts'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('amount'))), name='fee_invoice_lines_discount_within_amount'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['tenant', 'student', 'status'], name='fines_tenant__b3326f_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['tenant', 'source_module', 'source_reference'], name='fines_tenant__942198_idx'),
        ),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fines_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'waived'), _negated=True), models.Q(('waived_by__isnull', False), models.Q(('waived_reason', ''), _negated=True)), _connector='OR'), name='fines_waiver_is_attributable'),
        ),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('source_module__isnull', False), ('source_reference__isnull', False)), fields=('tenant', 'source_module', 'source_reference'), name='fines_source_unique'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['tenant', 'student', 'academic_session', 'status'], name='scholarship_tenant__5c99c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='scholarships_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('coverage_type', 'percent'), _negated=True), ('value__lte', 100), _connector='OR'), name='scholarships_percent_within_range'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'applied'), ('approved_by__isnull', False), _connector='OR'), name='scholarships_decision_is_attributable'),
        ),
    ]
