# Generated by Django 6.1 on 2026-09-07 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_finance', '0004_rls_policies'),
        ('files', '0002_rls_policies'),
        ('student_management', '0007_student_students_tenant_admitted_idx'),
        ('tenancy', '0006_tenantsettings_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank transfer'), ('card', 'Card'), ('online_gateway', 'Online gateway')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=80, null=True)),
                ('gateway_provider', models.CharField(blank=True, max_length=40, null=True)),
                ('gateway_payload', models.JSONField(blank=True, help_text='Sanitized confirmation snapshot. Never holds card data or credentials.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=15)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('received_by', models.UUIDField(blank=True, help_text='Null for a gateway or voucher self-service payment.', null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True)),
                ('fee_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees_finance.feeinvoice')),
                ('student', models.ForeignKey(help_text='Denormalized from the invoice so the student ledger is one query.', on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('bank_branch', 'Bank branch'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash')], max_length=40)),
                ('consumer_number', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void'), ('expired', 'Expired')], default='issued', max_length=15)),
                ('voided_reason', models.TextField(blank=True, null=True)),
                ('issued_by', models.UUIDField()),
                ('fee_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='fees_finance.feeinvoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_vouchers', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('payment', models.ForeignKey(blank=True, help_text='Set when a settlement row matches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='fees_finance.payment')),
            ],
            options={
                'db_table': 'fee_vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('receipt_no', models.CharField(max_length=30)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='fees_finance.payment')),
                ('pdf_file', models.ForeignKey(blank=True, db_column='pdf_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_receipts', to='files.file')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='requested', max_length=15)),
                ('requested_by', models.UUIDField()),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank transfer'), ('card', 'Card'), ('online_gateway', 'Online gateway')], max_length=20, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=80, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='fees_finance.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_refunds', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherCollectionImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('bank_branch', 'Bank branch'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash')], max_length=40)),
                ('imported_by', models.UUIDField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=15)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('exceptions', models.JSONField(blank=True, default=list, help_text='Unmatched rows: {row, provider_reference, amount, reason}.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.PROTECT, related_name='voucher_imports', to='files.file')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'voucher_collection_imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('bank_branch', 'Bank branch'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash')], max_length=40)),
                ('consumer_number', models.CharField(max_length=60)),
                ('transaction_reference', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField()),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_rows', to='fees_finance.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('voucher_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='fees_finance.vouchercollectionimport')),
            ],
            options={
                'db_table': 'voucher_settlement_rows',
                'ordering': ['-paid_on'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'fee_invoice'], name='payments_tenant__80bef2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'student', 'paid_at'], name='payments_tenant__903951_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'status', 'method'], name='payments_tenant__1ba04b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'confirmed'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='payments_confirmed_has_a_time'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'online_gateway'), _negated=True), ('gateway_provider__isnull', False), _connector='OR'), name='payments_gateway_names_its_provider'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='payments_idempotency_key_unique'),
        ),
        migrations.AddIndex(
            model_name='feevoucher',
            index=models.Index(fields=['tenant', 'fee_invoice'], name='fee_voucher_tenant__82ac35_idx'),
        ),
        migrations.AddIndex(
            model_name='feevoucher',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='fee_voucher_tenant__394c05_idx'),
        ),
        migrations.AddConstraint(
            model_name='feevoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'provider', 'consumer_number'), name='fee_vouchers_consumer_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='feevoucher',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fee_vouchers_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='feevoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), ('payment__isnull', False), _connector='OR'), name='fee_vouchers_paid_names_its_payment'),
        ),
        migrations.AddConstraint(
            model_name='feevoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'void'), _negated=True), models.Q(('voided_reason__isnull', False), models.Q(('voided_reason', ''), _negated=True)), _connector='OR'), name='fee_vouchers_void_is_attributable'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['tenant', 'issued_at'], name='receipts_tenant__56ba22_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'receipt_no'), name='receipts_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='receipts_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['tenant', 'status'], name='refunds_tenant__2d557c_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['tenant', 'payment'], name='refunds_tenant__8e6495_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['tenant', 'student'], name='refunds_tenant__c272f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refunds_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('requested_by')), _negated=True), _connector='OR'), name='refunds_approver_is_not_the_requester'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'requested'), ('approved_by__isnull', False), _connector='OR'), name='refunds_decision_is_attributable'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'processed'), _negated=True), models.Q(('processed_at__isnull', False), ('method__isnull', False)), _connector='OR'), name='refunds_processed_records_how_and_when'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='refunds_idempotency_key_unique'),
        ),
        migrations.AddIndex(
            model_name='vouchercollectionimport',
            index=models.Index(fields=['tenant', 'provider', 'created_at'], name='voucher_col_tenant__26be31_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchercollectionimport',
            index=models.Index(fields=['tenant', 'status'], name='voucher_col_tenant__3ab93b_idx'),
        ),
        migrations.AddConstraint(
            model_name='vouchercollectionimport',
            constraint=models.CheckConstraint(condition=models.Q(('matched_count__lte', models.F('row_count'))), name='voucher_imports_matched_within_rows'),
        ),
        migrations.AddIndex(
            model_name='settlementrow',
            index=models.Index(fields=['tenant', 'voucher_import'], name='voucher_set_tenant__b3bc6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementrow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'provider', 'consumer_number', 'transaction_reference'), name='settlement_rows_match_key_unique'),
        ),
    ]
