# Generated by Django 6.1 on 2026-09-08 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_finance', '0006_rls_policies'),
        ('files', '0002_rls_policies'),
        ('school_organization', '0002_rls_policies'),
        ('tenancy', '0006_tenantsettings_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='fees_finance.ledgeraccount')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='fees_finance.expensecategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'expense_categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expense_no', models.CharField(max_length=30)),
                ('vendor_name', models.CharField(blank=True, max_length=160, null=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Net of tax.', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank transfer'), ('card', 'Card'), ('online_gateway', 'Online gateway')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('campus', models.ForeignKey(blank=True, help_text='Null means the expense is not attributable to one campus.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='school_organization.campus')),
                ('receipt_file', models.ForeignKey(blank=True, db_column='receipt_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_receipts', to='files.file')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='fees_finance.expensecategory')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('closed', 'Closed')], default='draft', max_length=15)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(blank=True, help_text='Null means tenant-wide.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='school_organization.campus')),
                ('ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='fees_finance.ledgeraccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='fees_finance.expensecategory')),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'code'), name='expense_categories_code_unique'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'expense_category', 'expense_date'], name='expenses_tenant__d8409d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'status'], name='expenses_tenant__1bdc3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'expense_no'), name='expenses_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('tax_amount__gte', 0)), name='expenses_amounts_are_sane'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='expenses_approver_is_not_the_submitter'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted']), ('approved_by__isnull', False), _connector='OR'), name='expenses_decision_is_attributable'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method', 'online_gateway'), _negated=True), name='expenses_no_gateway_method'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tenant', 'period_start', 'period_end'], name='budgets_tenant__d2157b_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tenant', 'status'], name='budgets_tenant__acf4fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expense_category__isnull', True), ('ledger_account__isnull', False)), models.Q(('expense_category__isnull', False), ('ledger_account__isnull', True)), _connector='OR'), name='budgets_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='budgets_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='budgets_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('approved_by__isnull', False), _connector='OR'), name='budgets_approval_is_attributable'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('status', 'closed'), _negated=True)), fields=('tenant', 'ledger_account', 'expense_category', 'campus', 'period_start', 'period_end'), name='budgets_one_per_target_and_period', nulls_distinct=False),
        ),
    ]
