# Generated by Django 6.1 on 2026-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees_finance", "0008_rls_policies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                    ("reversed", "Reversed"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
    ]
