export * from "./base.page";
export * from "./dashboard/academics/promotion-batch.page";
export * from "./dashboard/dashboard.page";
export * from "./dashboard/login.page";
export * from "./dashboard/staff.page";
export * from "./dashboard/students/student-detail.page";
export * from "./dashboard/students/student-form.page";
export * from "./dashboard/timetable/week-grid.page";
export * from "./website/public-site.page";
