/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/academic-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Academic sessions and their lifecycle (module doc §5.4, §7).
         *
         *     No destroy: §16 exposes no DELETE and §4 grants no delete key. A session that
         *     should no longer be used is closed, which keeps its history addressable.
         */
        get: operations["academic_sessions_list"];
        put?: never;
        /**
         * @description Academic sessions and their lifecycle (module doc §5.4, §7).
         *
         *     No destroy: §16 exposes no DELETE and §4 grants no delete key. A session that
         *     should no longer be used is closed, which keeps its history addressable.
         */
        post: operations["academic_sessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Academic sessions and their lifecycle (module doc §5.4, §7).
         *
         *     No destroy: §16 exposes no DELETE and §4 grants no delete key. A session that
         *     should no longer be used is closed, which keeps its history addressable.
         */
        get: operations["academic_sessions_retrieve"];
        /**
         * @description Academic sessions and their lifecycle (module doc §5.4, §7).
         *
         *     No destroy: §16 exposes no DELETE and §4 grants no delete key. A session that
         *     should no longer be used is closed, which keeps its history addressable.
         */
        put: operations["academic_sessions_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Academic sessions and their lifecycle (module doc §5.4, §7).
         *
         *     No destroy: §16 exposes no DELETE and §4 grants no delete key. A session that
         *     should no longer be used is closed, which keeps its history addressable.
         */
        patch: operations["academic_sessions_partial_update"];
        trace?: never;
    };
    "/api/v1/academic-sessions/{id}:activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate an academic session
         * @description Academic sessions and their lifecycle (module doc §5.4, §7).
         *
         *     No destroy: §16 exposes no DELETE and §4 grants no delete key. A session that
         *     should no longer be used is closed, which keeps its history addressable.
         */
        post: operations["academic_sessions_:activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-sessions/{id}:clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone a session's curriculum into a new session
         * @description Academic sessions and their lifecycle (module doc §5.4, §7).
         *
         *     No destroy: §16 exposes no DELETE and §4 grants no delete key. A session that
         *     should no longer be used is closed, which keeps its history addressable.
         */
        post: operations["academic_sessions_:clone_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-sessions/{id}:close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close an academic session
         * @description Academic sessions and their lifecycle (module doc §5.4, §7).
         *
         *     No destroy: §16 exposes no DELETE and §4 grants no delete key. A session that
         *     should no longer be used is closed, which keeps its history addressable.
         */
        post: operations["academic_sessions_:close_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The authenticated principal, with effective permissions for UI gating. */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Rotating refresh. Reuse of a rotated token invalidates the family (theft detection).
         *
         *     The refresh token travels only in ``REFRESH_COOKIE_NAME`` — never in the request
         *     body — so this cannot reuse ``TokenRefreshView`` (which reads the body) even though
         *     it delegates the actual rotation logic to simplejwt's own serializer.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Campuses/branches of the school (module doc §5.2). */
        get: operations["campuses_list"];
        put?: never;
        /** @description Campuses/branches of the school (module doc §5.2). */
        post: operations["campuses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campuses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Campuses/branches of the school (module doc §5.2). */
        get: operations["campuses_retrieve"];
        /** @description Campuses/branches of the school (module doc §5.2). */
        put: operations["campuses_update"];
        post?: never;
        /** @description Campuses/branches of the school (module doc §5.2). */
        delete: operations["campuses_destroy"];
        options?: never;
        head?: never;
        /** @description Campuses/branches of the school (module doc §5.2). */
        patch: operations["campuses_partial_update"];
        trace?: never;
    };
    "/api/v1/class-subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curriculum mapping of subjects onto classes for one session.
         *
         *     Shares the subject permission keys: mapping a subject to a class is subject
         *     management, and §4 declares no separate key for it.
         */
        get: operations["class_subjects_list"];
        put?: never;
        /**
         * @description Curriculum mapping of subjects onto classes for one session.
         *
         *     Shares the subject permission keys: mapping a subject to a class is subject
         *     management, and §4 declares no separate key for it.
         */
        post: operations["class_subjects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/class-subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curriculum mapping of subjects onto classes for one session.
         *
         *     Shares the subject permission keys: mapping a subject to a class is subject
         *     management, and §4 declares no separate key for it.
         */
        get: operations["class_subjects_retrieve"];
        /**
         * @description Curriculum mapping of subjects onto classes for one session.
         *
         *     Shares the subject permission keys: mapping a subject to a class is subject
         *     management, and §4 declares no separate key for it.
         */
        put: operations["class_subjects_update"];
        post?: never;
        /**
         * @description Curriculum mapping of subjects onto classes for one session.
         *
         *     Shares the subject permission keys: mapping a subject to a class is subject
         *     management, and §4 declares no separate key for it.
         */
        delete: operations["class_subjects_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Curriculum mapping of subjects onto classes for one session.
         *
         *     Shares the subject permission keys: mapping a subject to a class is subject
         *     management, and §4 declares no separate key for it.
         */
        patch: operations["class_subjects_partial_update"];
        trace?: never;
    };
    "/api/v1/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Grade levels; ``level`` is the promotion ladder (module doc §5.5). */
        get: operations["classes_list"];
        put?: never;
        /** @description Grade levels; ``level`` is the promotion ladder (module doc §5.5). */
        post: operations["classes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Grade levels; ``level`` is the promotion ladder (module doc §5.5). */
        get: operations["classes_retrieve"];
        /** @description Grade levels; ``level`` is the promotion ladder (module doc §5.5). */
        put: operations["classes_update"];
        post?: never;
        /** @description Grade levels; ``level`` is the promotion ladder (module doc §5.5). */
        delete: operations["classes_destroy"];
        options?: never;
        head?: never;
        /** @description Grade levels; ``level`` is the promotion ladder (module doc §5.5). */
        patch: operations["classes_partial_update"];
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Academic and administrative departments (module doc §5.3). */
        get: operations["departments_list"];
        put?: never;
        /** @description Academic and administrative departments (module doc §5.3). */
        post: operations["departments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Academic and administrative departments (module doc §5.3). */
        get: operations["departments_retrieve"];
        /** @description Academic and administrative departments (module doc §5.3). */
        put: operations["departments_update"];
        post?: never;
        /** @description Academic and administrative departments (module doc §5.3). */
        delete: operations["departments_destroy"];
        options?: never;
        head?: never;
        /** @description Academic and administrative departments (module doc §5.3). */
        patch: operations["departments_partial_update"];
        trace?: never;
    };
    "/api/v1/houses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Houses/groups used for sports, discipline and points (module doc §5.7). */
        get: operations["houses_list"];
        put?: never;
        /** @description Houses/groups used for sports, discipline and points (module doc §5.7). */
        post: operations["houses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/houses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Houses/groups used for sports, discipline and points (module doc §5.7). */
        get: operations["houses_retrieve"];
        /** @description Houses/groups used for sports, discipline and points (module doc §5.7). */
        put: operations["houses_update"];
        post?: never;
        /** @description Houses/groups used for sports, discipline and points (module doc §5.7). */
        delete: operations["houses_destroy"];
        options?: never;
        head?: never;
        /** @description Houses/groups used for sports, discipline and points (module doc §5.7). */
        patch: operations["houses_partial_update"];
        trace?: never;
    };
    "/api/v1/school-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Singleton school profile and academic configuration (module doc §16).
         *
         *     A singleton rather than a collection because a tenant is one school; the
         *     branding/academic payloads live in ``tenant_settings`` JSONB while timezone,
         *     locale and currency stay on the tenant row, which is where the request
         *     middleware and every other module already read them from.
         */
        get: operations["school_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Singleton school profile and academic configuration (module doc §16).
         *
         *     A singleton rather than a collection because a tenant is one school; the
         *     branding/academic payloads live in ``tenant_settings`` JSONB while timezone,
         *     locale and currency stay on the tenant row, which is where the request
         *     middleware and every other module already read them from.
         */
        patch: operations["school_settings_partial_update"];
        trace?: never;
    };
    "/api/v1/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Divisions of a class at a campus, with capacity (module doc §5.5). */
        get: operations["sections_list"];
        put?: never;
        /** @description Divisions of a class at a campus, with capacity (module doc §5.5). */
        post: operations["sections_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Divisions of a class at a campus, with capacity (module doc §5.5). */
        get: operations["sections_retrieve"];
        /** @description Divisions of a class at a campus, with capacity (module doc §5.5). */
        put: operations["sections_update"];
        post?: never;
        /** @description Divisions of a class at a campus, with capacity (module doc §5.5). */
        delete: operations["sections_destroy"];
        options?: never;
        head?: never;
        /** @description Divisions of a class at a campus, with capacity (module doc §5.5). */
        patch: operations["sections_partial_update"];
        trace?: never;
    };
    "/api/v1/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Student master records (module doc §5.1-2). */
        get: operations["students_list"];
        put?: never;
        /** @description Student master records (module doc §5.1-2). */
        post: operations["students_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Student master records (module doc §5.1-2). */
        get: operations["students_retrieve"];
        put?: never;
        post?: never;
        /** @description Student master records (module doc §5.1-2). */
        delete: operations["students_destroy"];
        options?: never;
        head?: never;
        /** @description Student master records (module doc §5.1-2). */
        patch: operations["students_partial_update"];
        trace?: never;
    };
    "/api/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The tenant's subject catalog (module doc §5.6). */
        get: operations["subjects_list"];
        put?: never;
        /** @description The tenant's subject catalog (module doc §5.6). */
        post: operations["subjects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The tenant's subject catalog (module doc §5.6). */
        get: operations["subjects_retrieve"];
        /** @description The tenant's subject catalog (module doc §5.6). */
        put: operations["subjects_update"];
        post?: never;
        /** @description The tenant's subject catalog (module doc §5.6). */
        delete: operations["subjects_destroy"];
        options?: never;
        head?: never;
        /** @description The tenant's subject catalog (module doc §5.6). */
        patch: operations["subjects_partial_update"];
        trace?: never;
    };
    "/api/v1/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Terms of a session. Governed by the academic-session permission keys (§4). */
        get: operations["terms_list"];
        put?: never;
        /** @description Terms of a session. Governed by the academic-session permission keys (§4). */
        post: operations["terms_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Terms of a session. Governed by the academic-session permission keys (§4). */
        get: operations["terms_retrieve"];
        /** @description Terms of a session. Governed by the academic-session permission keys (§4). */
        put: operations["terms_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Terms of a session. Governed by the academic-session permission keys (§4). */
        patch: operations["terms_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcademicSession: {
            /** Format: uuid */
            readonly id: string;
            /** @description School year label, e.g. "2026–27". */
            name: string;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            readonly status: components["schemas"]["AcademicSessionStatusEnum"];
            readonly is_current: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `planned` - Planned
         *     * `active` - Active
         *     * `closed` - Closed
         *     * `archived` - Archived
         * @enum {string}
         */
        AcademicSessionStatusEnum: "planned" | "active" | "closed" | "archived";
        Campus: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            code: string;
            address?: unknown;
            phone?: string | null;
            email?: (string) | null;
            /** @description IANA identifier. Null inherits the tenant timezone. */
            timezone?: string | null;
            /**
             * Format: uuid
             * @description staff(id) — campus head.
             */
            head_staff_id?: string | null;
            is_primary?: boolean;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ChangePassword: {
            current_password: string;
            new_password: string;
        };
        Class: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            code?: string | null;
            /** @description Promotion ordering; the next level up is the promotion target. */
            level: number;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Curriculum mapping: this class studies this subject in this session. */
        ClassSubject: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            academic_session_id: string;
            /** Format: uuid */
            class_id: string;
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            campus_id?: string | null;
            is_elective?: boolean;
            /** @description Options sharing a group are mutually choosable ("choose 1 of N"). */
            elective_group?: string | null;
            /** @description Target periods per week. */
            weekly_periods?: number;
            /**
             * Format: uuid
             * @description files(id).
             */
            syllabus_file_id?: string | null;
            /** @description [{term_id, topics: [...]}] per-term topic plan. */
            term_plans?: unknown;
            notes?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Department: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            code: string;
            department_type?: components["schemas"]["DepartmentTypeEnum"];
            /** Format: uuid */
            campus_id?: string | null;
            /**
             * Format: uuid
             * @description staff(id) — head of dept.
             */
            head_staff_id?: string | null;
            description?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `academic` - Academic
         *     * `administrative` - Administrative
         * @enum {string}
         */
        DepartmentTypeEnum: "academic" | "administrative";
        /**
         * @description * `male` - Male
         *     * `female` - Female
         *     * `other` - Other
         *     * `unspecified` - Unspecified
         * @enum {string}
         */
        GenderEnum: "male" | "female" | "other" | "unspecified";
        House: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            code?: string | null;
            /** @description Token or hex. */
            color?: string | null;
            motto?: string | null;
            /**
             * Format: uuid
             * @description staff(id).
             */
            house_master_staff_id?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Email/username + password login.
         *
         *     Deliberately returns the same generic error for unknown accounts and wrong
         *     passwords so the endpoint cannot be used to enumerate who has an account at
         *     a school.
         */
        Login: {
            identifier: string;
            password: string;
            /** @description Tenant slug. Required only when the identifier exists at more than one school. */
            school?: string;
        };
        PaginatedAcademicSessionList: {
            data?: components["schemas"]["AcademicSession"][];
            meta?: {
                pagination?: {
                    next_cursor?: string | null;
                    previous_cursor?: string | null;
                    page_size?: number;
                };
            };
        };
        PaginatedCampusList: {
            data?: components["schemas"]["Campus"][];
            meta?: {
                pagination?: {
                    next_cursor?: string | null;
                    previous_cursor?: string | null;
                    page_size?: number;
                };
            };
        };
        PaginatedClassList: {
            data?: components["schemas"]["Class"][];
            meta?: {
                pagination?: {
                    next_cursor?: string | null;
                    previous_cursor?: string | null;
                    page_size?: number;
                };
            };
        };
        PaginatedClassSubjectList: {
            data?: components["schemas"]["ClassSubject"][];
            meta?: {
                pagination?: {
                    next_cursor?: string | null;
                    previous_cursor?: string | null;
                    page_size?: number;
                };
            };
        };
        PaginatedDepartmentList: {
            data?: components["schemas"]["Department"][];
            meta?: {
                pagination?: {
                    next_cursor?: string | null;
                    previous_cursor?: string | null;
                    page_size?: number;
                };
            };
        };
        PaginatedHouseList: {
            data?: components["schemas"]["House"][];
            meta?: {
                pagination?: {
                    next_cursor?: string | null;
                    previous_cursor?: string | null;
                    page_size?: number;
                };
            };
        };
        PaginatedSectionList: {
            data?: components["schemas"]["Section"][];
            meta?: {
                pagination?: {
                    next_cursor?: string | null;
                    previous_cursor?: string | null;
                    page_size?: number;
                };
            };
        };
        PaginatedStudentList: {
            data?: components["schemas"]["Student"][];
            meta?: {
                pagination?: {
                    next_cursor?: string | null;
                    previous_cursor?: string | null;
                    page_size?: number;
                };
            };
        };
        PaginatedSubjectList: {
            data?: components["schemas"]["Subject"][];
            meta?: {
                pagination?: {
                    next_cursor?: string | null;
                    previous_cursor?: string | null;
                    page_size?: number;
                };
            };
        };
        PaginatedTermList: {
            data?: components["schemas"]["Term"][];
            meta?: {
                pagination?: {
                    next_cursor?: string | null;
                    previous_cursor?: string | null;
                    page_size?: number;
                };
            };
        };
        PatchedAcademicSession: {
            /** Format: uuid */
            readonly id?: string;
            /** @description School year label, e.g. "2026–27". */
            name?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            readonly status?: components["schemas"]["AcademicSessionStatusEnum"];
            readonly is_current?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedCampus: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            code?: string;
            address?: unknown;
            phone?: string | null;
            email?: (string) | null;
            /** @description IANA identifier. Null inherits the tenant timezone. */
            timezone?: string | null;
            /**
             * Format: uuid
             * @description staff(id) — campus head.
             */
            head_staff_id?: string | null;
            is_primary?: boolean;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedClass: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            code?: string | null;
            /** @description Promotion ordering; the next level up is the promotion target. */
            level?: number;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Curriculum mapping: this class studies this subject in this session. */
        PatchedClassSubject: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            academic_session_id?: string;
            /** Format: uuid */
            class_id?: string;
            /** Format: uuid */
            subject_id?: string;
            /** Format: uuid */
            campus_id?: string | null;
            is_elective?: boolean;
            /** @description Options sharing a group are mutually choosable ("choose 1 of N"). */
            elective_group?: string | null;
            /** @description Target periods per week. */
            weekly_periods?: number;
            /**
             * Format: uuid
             * @description files(id).
             */
            syllabus_file_id?: string | null;
            /** @description [{term_id, topics: [...]}] per-term topic plan. */
            term_plans?: unknown;
            notes?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedDepartment: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            code?: string;
            department_type?: components["schemas"]["DepartmentTypeEnum"];
            /** Format: uuid */
            campus_id?: string | null;
            /**
             * Format: uuid
             * @description staff(id) — head of dept.
             */
            head_staff_id?: string | null;
            description?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedHouse: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            code?: string | null;
            /** @description Token or hex. */
            color?: string | null;
            motto?: string | null;
            /**
             * Format: uuid
             * @description staff(id).
             */
            house_master_staff_id?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /**
         * @description School profile and academic configuration (module doc §16, singleton resource).
         *
         *     Backed by ``tenant_settings`` JSONB rather than its own table: the shape is
         *     tenant-configurable (accreditation fields, holiday calendar, weekend definition)
         *     and columns would force a migration per school that wants one more field.
         */
        PatchedSchoolSettings: {
            branding?: unknown;
            academic?: unknown;
            timezone?: string;
            locale?: string;
            currency?: string;
        };
        PatchedSection: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            class_id?: string;
            /** Format: uuid */
            campus_id?: string;
            /** @description Division label, e.g. "A". */
            name?: string;
            /** @description Enrollment ceiling. Null means unlimited. */
            capacity?: number | null;
            /**
             * Format: uuid
             * @description staff(id) — homeroom teacher.
             */
            class_teacher_staff_id?: string | null;
            /**
             * Format: uuid
             * @description rooms(id) — default homeroom.
             */
            room_id?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedStudent: {
            /** Format: uuid */
            readonly id?: string;
            admission_number?: string;
            /**
             * Format: uuid
             * @description users(id) — portal account, tenant-checked at write time.
             */
            user_id?: string | null;
            first_name?: string;
            last_name?: string;
            preferred_name?: string | null;
            /** Format: date */
            date_of_birth?: string;
            gender?: components["schemas"]["GenderEnum"];
            /**
             * Format: uuid
             * @description files(id) — promoted when core.files lands.
             */
            photo_file_id?: string | null;
            /** Format: uuid */
            campus_id?: string;
            /** Format: uuid */
            house_id?: string | null;
            readonly status?: components["schemas"]["StudentStatusEnum"];
            /** Format: date */
            admission_date?: string;
            blood_group?: string | null;
            nationality?: string | null;
            /** @description Optional/sensitive; a tenant may disable. */
            religion?: string | null;
            previous_school?: string | null;
            /** @description Restricted visibility — see serializers.StudentSerializer.to_representation and core.audit.services._REDACTED_FIELDS. */
            medical_notes?: string | null;
            address?: unknown;
            custom_fields?: unknown;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedSubject: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            code?: string;
            subject_type?: components["schemas"]["SubjectTypeEnum"];
            /** Format: uuid */
            department_id?: string | null;
            description?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedTerm: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            academic_session_id?: string;
            name?: string;
            /** @description Order within the session, 1-based. */
            sequence?: number;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /**
         * @description Documents ``RefreshView``'s actual response body for the OpenAPI schema.
         *
         *     Read-only and never instantiated to validate input — ``RefreshView`` builds this
         *     shape itself from a rotated token, this exists purely so ``@extend_schema`` can
         *     describe the real response instead of claiming an empty body.
         */
        RefreshResponse: {
            access_token: string;
            expires_in: number;
        };
        /**
         * @description School profile and academic configuration (module doc §16, singleton resource).
         *
         *     Backed by ``tenant_settings`` JSONB rather than its own table: the shape is
         *     tenant-configurable (accreditation fields, holiday calendar, weekend definition)
         *     and columns would force a migration per school that wants one more field.
         */
        SchoolSettings: {
            branding?: unknown;
            academic?: unknown;
            timezone?: string;
            locale?: string;
            currency?: string;
        };
        Section: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            class_id: string;
            /** Format: uuid */
            campus_id: string;
            /** @description Division label, e.g. "A". */
            name: string;
            /** @description Enrollment ceiling. Null means unlimited. */
            capacity?: number | null;
            /**
             * Format: uuid
             * @description staff(id) — homeroom teacher.
             */
            class_teacher_staff_id?: string | null;
            /**
             * Format: uuid
             * @description rooms(id) — default homeroom.
             */
            room_id?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Input for ``POST /academic-sessions/{id}:clone`` — the new session's identity. */
        SessionClone: {
            name: string;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
        };
        Student: {
            /** Format: uuid */
            readonly id: string;
            admission_number?: string;
            /**
             * Format: uuid
             * @description users(id) — portal account, tenant-checked at write time.
             */
            user_id?: string | null;
            first_name: string;
            last_name: string;
            preferred_name?: string | null;
            /** Format: date */
            date_of_birth: string;
            gender: components["schemas"]["GenderEnum"];
            /**
             * Format: uuid
             * @description files(id) — promoted when core.files lands.
             */
            photo_file_id?: string | null;
            /** Format: uuid */
            campus_id: string;
            /** Format: uuid */
            house_id?: string | null;
            readonly status: components["schemas"]["StudentStatusEnum"];
            /** Format: date */
            admission_date: string;
            blood_group?: string | null;
            nationality?: string | null;
            /** @description Optional/sensitive; a tenant may disable. */
            religion?: string | null;
            previous_school?: string | null;
            /** @description Restricted visibility — see serializers.StudentSerializer.to_representation and core.audit.services._REDACTED_FIELDS. */
            medical_notes?: string | null;
            address?: unknown;
            custom_fields?: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `active` - Active
         *     * `suspended` - Suspended
         *     * `transferred` - Transferred
         *     * `withdrawn` - Withdrawn
         *     * `graduated` - Graduated
         * @enum {string}
         */
        StudentStatusEnum: "active" | "suspended" | "transferred" | "withdrawn" | "graduated";
        Subject: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            code: string;
            subject_type?: components["schemas"]["SubjectTypeEnum"];
            /** Format: uuid */
            department_id?: string | null;
            description?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `core` - Core
         *     * `elective` - Elective
         *     * `co_curricular` - Co-curricular
         * @enum {string}
         */
        SubjectTypeEnum: "core" | "elective" | "co_curricular";
        Term: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            academic_session_id: string;
            name: string;
            /** @description Order within the session, 1-based. */
            sequence: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        User: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            /** @description School-issued login for students without email. */
            readonly username: string | null;
            readonly first_name: string;
            readonly last_name: string;
            readonly full_name: string;
            readonly phone: string;
            /** Format: uuid */
            readonly tenant: string | null;
            /** @description Platform-scope principal (no tenant). */
            readonly is_platform: boolean;
            readonly mfa_enabled: boolean;
            readonly permissions: string[];
            readonly roles: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    academic_sessions_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                is_current?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `planned` - Planned
                 *     * `active` - Active
                 *     * `closed` - Closed
                 *     * `archived` - Archived
                 */
                status?: "active" | "archived" | "closed" | "planned";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAcademicSessionList"];
                };
            };
        };
    };
    academic_sessions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcademicSession"];
                "application/x-www-form-urlencoded": components["schemas"]["AcademicSession"];
                "multipart/form-data": components["schemas"]["AcademicSession"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicSession"];
                };
            };
        };
    };
    academic_sessions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this academic session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicSession"];
                };
            };
        };
    };
    academic_sessions_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this academic session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcademicSession"];
                "application/x-www-form-urlencoded": components["schemas"]["AcademicSession"];
                "multipart/form-data": components["schemas"]["AcademicSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicSession"];
                };
            };
        };
    };
    academic_sessions_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this academic session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAcademicSession"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAcademicSession"];
                "multipart/form-data": components["schemas"]["PatchedAcademicSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicSession"];
                };
            };
        };
    };
    "academic_sessions_:activate_create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicSession"];
                };
            };
            /** @description Structure incomplete for activation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "academic_sessions_:clone_create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionClone"];
                "application/x-www-form-urlencoded": components["schemas"]["SessionClone"];
                "multipart/form-data": components["schemas"]["SessionClone"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicSession"];
                };
            };
        };
    };
    "academic_sessions_:close_create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicSession"];
                };
            };
            /** @description Not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePassword"];
                "multipart/form-data": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    campuses_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                is_active?: boolean;
                is_primary?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCampusList"];
                };
            };
        };
    };
    campuses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Campus"];
                "application/x-www-form-urlencoded": components["schemas"]["Campus"];
                "multipart/form-data": components["schemas"]["Campus"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campus"];
                };
            };
        };
    };
    campuses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this campus. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campus"];
                };
            };
        };
    };
    campuses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this campus. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Campus"];
                "application/x-www-form-urlencoded": components["schemas"]["Campus"];
                "multipart/form-data": components["schemas"]["Campus"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campus"];
                };
            };
        };
    };
    campuses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this campus. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    campuses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this campus. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCampus"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCampus"];
                "multipart/form-data": components["schemas"]["PatchedCampus"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campus"];
                };
            };
        };
    };
    class_subjects_list: {
        parameters: {
            query?: {
                academic_session_id?: string;
                campus_id?: string;
                class_id?: string;
                /** @description The pagination cursor value. */
                cursor?: string;
                elective_group?: string;
                is_elective?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                subject_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedClassSubjectList"];
                };
            };
        };
    };
    class_subjects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassSubject"];
                "application/x-www-form-urlencoded": components["schemas"]["ClassSubject"];
                "multipart/form-data": components["schemas"]["ClassSubject"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSubject"];
                };
            };
        };
    };
    class_subjects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this class subject. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSubject"];
                };
            };
        };
    };
    class_subjects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this class subject. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassSubject"];
                "application/x-www-form-urlencoded": components["schemas"]["ClassSubject"];
                "multipart/form-data": components["schemas"]["ClassSubject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSubject"];
                };
            };
        };
    };
    class_subjects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this class subject. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    class_subjects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this class subject. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedClassSubject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedClassSubject"];
                "multipart/form-data": components["schemas"]["PatchedClassSubject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSubject"];
                };
            };
        };
    };
    classes_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                is_active?: boolean;
                level?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedClassList"];
                };
            };
        };
    };
    classes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Class"];
                "application/x-www-form-urlencoded": components["schemas"]["Class"];
                "multipart/form-data": components["schemas"]["Class"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this class. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this class. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Class"];
                "application/x-www-form-urlencoded": components["schemas"]["Class"];
                "multipart/form-data": components["schemas"]["Class"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this class. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    classes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this class. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedClass"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedClass"];
                "multipart/form-data": components["schemas"]["PatchedClass"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    departments_list: {
        parameters: {
            query?: {
                campus_id?: string;
                /** @description The pagination cursor value. */
                cursor?: string;
                /**
                 * @description * `academic` - Academic
                 *     * `administrative` - Administrative
                 */
                department_type?: "academic" | "administrative";
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDepartmentList"];
                };
            };
        };
    };
    departments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Department"];
                "application/x-www-form-urlencoded": components["schemas"]["Department"];
                "multipart/form-data": components["schemas"]["Department"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Department"];
                "application/x-www-form-urlencoded": components["schemas"]["Department"];
                "multipart/form-data": components["schemas"]["Department"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    departments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDepartment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDepartment"];
                "multipart/form-data": components["schemas"]["PatchedDepartment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    houses_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHouseList"];
                };
            };
        };
    };
    houses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["House"];
                "application/x-www-form-urlencoded": components["schemas"]["House"];
                "multipart/form-data": components["schemas"]["House"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["House"];
                };
            };
        };
    };
    houses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this house. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["House"];
                };
            };
        };
    };
    houses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this house. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["House"];
                "application/x-www-form-urlencoded": components["schemas"]["House"];
                "multipart/form-data": components["schemas"]["House"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["House"];
                };
            };
        };
    };
    houses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this house. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    houses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this house. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedHouse"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedHouse"];
                "multipart/form-data": components["schemas"]["PatchedHouse"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["House"];
                };
            };
        };
    };
    school_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolSettings"];
                };
            };
        };
    };
    school_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSchoolSettings"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSchoolSettings"];
                "multipart/form-data": components["schemas"]["PatchedSchoolSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolSettings"];
                };
            };
        };
    };
    sections_list: {
        parameters: {
            query?: {
                campus_id?: string;
                class_id?: string;
                /** @description The pagination cursor value. */
                cursor?: string;
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSectionList"];
                };
            };
        };
    };
    sections_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Section"];
                "application/x-www-form-urlencoded": components["schemas"]["Section"];
                "multipart/form-data": components["schemas"]["Section"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
        };
    };
    sections_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this section. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
        };
    };
    sections_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this section. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Section"];
                "application/x-www-form-urlencoded": components["schemas"]["Section"];
                "multipart/form-data": components["schemas"]["Section"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
        };
    };
    sections_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this section. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sections_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this section. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSection"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSection"];
                "multipart/form-data": components["schemas"]["PatchedSection"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
        };
    };
    students_list: {
        parameters: {
            query?: {
                campus_id?: string;
                /** @description The pagination cursor value. */
                cursor?: string;
                house_id?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `active` - Active
                 *     * `suspended` - Suspended
                 *     * `transferred` - Transferred
                 *     * `withdrawn` - Withdrawn
                 *     * `graduated` - Graduated
                 */
                status?: "active" | "graduated" | "suspended" | "transferred" | "withdrawn";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStudentList"];
                };
            };
        };
    };
    students_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Student"];
                "application/x-www-form-urlencoded": components["schemas"]["Student"];
                "multipart/form-data": components["schemas"]["Student"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    students_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this student. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    students_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this student. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    students_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this student. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStudent"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStudent"];
                "multipart/form-data": components["schemas"]["PatchedStudent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    subjects_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                department_id?: string;
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `core` - Core
                 *     * `elective` - Elective
                 *     * `co_curricular` - Co-curricular
                 */
                subject_type?: "co_curricular" | "core" | "elective";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubjectList"];
                };
            };
        };
    };
    subjects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Subject"];
                "application/x-www-form-urlencoded": components["schemas"]["Subject"];
                "multipart/form-data": components["schemas"]["Subject"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    subjects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this subject. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    subjects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this subject. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Subject"];
                "application/x-www-form-urlencoded": components["schemas"]["Subject"];
                "multipart/form-data": components["schemas"]["Subject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    subjects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this subject. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    subjects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this subject. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSubject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSubject"];
                "multipart/form-data": components["schemas"]["PatchedSubject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    terms_list: {
        parameters: {
            query?: {
                academic_session_id?: string;
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTermList"];
                };
            };
        };
    };
    terms_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Term"];
                "application/x-www-form-urlencoded": components["schemas"]["Term"];
                "multipart/form-data": components["schemas"]["Term"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Term"];
                };
            };
        };
    };
    terms_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this term. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Term"];
                };
            };
        };
    };
    terms_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this term. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Term"];
                "application/x-www-form-urlencoded": components["schemas"]["Term"];
                "multipart/form-data": components["schemas"]["Term"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Term"];
                };
            };
        };
    };
    terms_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this term. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTerm"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTerm"];
                "multipart/form-data": components["schemas"]["PatchedTerm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Term"];
                };
            };
        };
    };
}
