# Generated by Django 6.1 on 2026-09-03 03:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('storage_key', models.CharField(help_text='Object-storage key, prefixed tenants/{tenant_id}/… (multi-tenancy.md §3).', max_length=512, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('purpose', models.CharField(help_text="What this file is for, e.g. 'student.photo', 'student.document'.", max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('quarantined', 'Quarantined')], default='pending', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20)),
                ('av_scanned_at', models.DateTimeField(blank=True, help_text='Set once an AV scan has run. No scanner is wired up yet (see core.files.tasks docstring) — this column exists so the contract is in place before the scanner is, not because scanning happens today.', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'purpose'], name='files_tenant_purpose_idx'), models.Index(fields=['tenant', 'status'], name='files_tenant_status_idx')],
            },
        ),
    ]
