# Generated by Django 6.1 on 2026-09-05 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_organization', '0002_rls_policies'),
        ('staff_management', '0002_rls_policies'),
        ('student_management', '0006_rls_policies'),
        ('tenancy', '0005_tenantsettings_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('batch_id', models.UUIDField(help_text='Logical batch grouping — one per class per rollover. No batch table.')),
                ('decision', models.CharField(choices=[('promoted', 'Promoted'), ('retained', 'Retained'), ('promoted_on_trial', 'Promoted on trial'), ('graduated', 'Graduated')], max_length=30)),
                ('decision_basis', models.JSONField(blank=True, help_text='Snapshot of result aggregates, attendance %, rule evaluation at proposal time.', null=True)),
                ('override_reason', models.CharField(blank=True, help_text='Required when the decision deviates from the rule proposal.', max_length=500, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('executed', 'Executed'), ('reverted', 'Reverted')], default='draft', max_length=30)),
                ('approved_by', models.UUIDField(blank=True, help_text='users(id) — must differ from the preparer.', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('from_academic_session', models.ForeignKey(db_column='from_academic_session_id', on_delete=django.db.models.deletion.PROTECT, related_name='promotions_from', to='school_organization.academicsession')),
                ('from_class', models.ForeignKey(db_column='from_class_id', on_delete=django.db.models.deletion.PROTECT, related_name='promotions_from', to='school_organization.class')),
                ('from_enrollment', models.ForeignKey(db_column='from_enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='student_management.studentenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='student_management.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('to_academic_session', models.ForeignKey(db_column='to_academic_session_id', on_delete=django.db.models.deletion.PROTECT, related_name='promotions_to', to='school_organization.academicsession')),
                ('to_class', models.ForeignKey(blank=True, db_column='to_class_id', help_text='Null when decision = graduated.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_to', to='school_organization.class')),
                ('to_section', models.ForeignKey(blank=True, db_column='to_section_id', help_text='Assigned at or before execution.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_to', to='school_organization.section')),
            ],
            options={
                'db_table': 'student_promotions',
                'ordering': ['student_id'],
                'indexes': [models.Index(fields=['tenant', 'batch_id', 'status'], name='promotions_batch_idx'), models.Index(fields=['tenant', 'student'], name='promotions_student_idx'), models.Index(fields=['tenant', 'to_academic_session'], name='promotions_to_session_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'batch_id', 'student'), name='promotions_unique_student_per_batch'), models.CheckConstraint(condition=models.Q(models.Q(('decision', 'graduated'), ('to_class__isnull', True)), models.Q(models.Q(('decision', 'graduated'), _negated=True), ('to_class__isnull', False)), _connector='OR'), name='promotions_target_class_matches_decision'), models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True)), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='promotions_approval_fields_together')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_primary', models.BooleanField(default=True, help_text='One primary per (section, subject); others are co-teachers.')),
                ('weekly_periods', models.PositiveSmallIntegerField(blank=True, help_text="Overrides class_subjects.weekly_periods for this allocation's load math.", null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Null = current. Set rather than deleted on reassignment.', null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_allocations', to='school_organization.academicsession')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_allocations', to='school_organization.section')),
                ('staff', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.PROTECT, related_name='subject_allocations', to='staff_management.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_allocations', to='school_organization.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'teacher_subject_allocations',
                'ordering': ['section_id', 'subject_id'],
                'indexes': [models.Index(fields=['tenant', 'staff', 'academic_session'], name='tsa_tenant_staff_idx'), models.Index(fields=['tenant', 'section', 'subject'], name='tsa_section_subject_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'academic_session', 'section', 'subject', 'staff'), name='tsa_unique_allocation'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('effective_to__isnull', True), ('is_primary', True)), fields=('tenant', 'academic_session', 'section', 'subject'), name='tsa_one_primary_per_section_subject'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='tsa_effective_range_ordered')],
            },
        ),
    ]
